### PR TITLE
Anvil: fix rotation and drops the way it should be done

### PR DESCRIPTION
**Pull request by dktapps**
Using bitwise operators the right way.

Tests: Tested, everything works.

(I also reformatted the file with tabs since spaces + me = OCD and the formatting was all over the place)

### CODE REVIEW

**Comment by robske110** [comment]
👍
Travis hurry up

**Comment by robske110** [comment]
Travis died. Why?

**Comment by dktapps** [comment]
@robske110 might be a sync glitch, check the website

**Comment by robske110** [comment]
Travis!!!!!

**Comment by robske110** [comment]
Fuck this

**Comment by inxomnyaa** [comment]
I already contacted github, they fixed it

**Pull request merged**
