### PR TITLE
An (maybe) working upgrader

### PR DESCRIPTION
**Pull request by robske110**
In progress

### CODE REVIEW

**Comment by robske110** [comment]
The problem is: how should i test it?

**Comment by Aericio** [comment]
Go to a lower version and see if it auto-updates?

**Comment by robske110** [comment]
?! Then this fix wouldn't be in it

**Comment by Aericio** [comment]
Oh. I see what you mean...

**Comment by inxomnyaa** [comment]
merge, and do another test pr

**Comment by aodzip** [comment]
edit Build string in pocketmine.php and makeserver

**Comment by robske110** [comment]
Ok, will try that out

**Pull request merged**
