### PR TITLE
Update Slimeblock.php

### PR DESCRIPTION
**Pull request by ghost**
meta ...

### CODE REVIEW

**Comment by DaPigGuy** [comment]
Since when did slime blocks have different damage values that actually change how they look?

**Comment by robske110** [comment]
idk
They have no different values.

**Comment by DaPigGuy** [comment]
then why is this merged...

**Comment by robske110** [comment]
Should i revert it?

**Comment by DaPigGuy** [comment]
probably :stuck_out_tongue_winking_eye:

**Comment by inxomnyaa** [comment]
WHAT THE FUCK MAN YOU MERGE WITHOUT THINKING!
WHAT IS WITH THE OLD "HEY DAN IS IT OKAY TO MERGE THIS SHIT"?!

**Comment by robske110** [comment]
That's why i wanted to get that pr accept in here

**Comment by dktapps** [comment]
PullApprove you mean @robske110?

**Comment by robske110** [comment]
Yep

**Pull request merged**
