### PR TITLE
Added language selection

### PR DESCRIPTION
**Pull request by ondraczsk**
language selection on readme

### CODE REVIEW

**Comment by MasterWolf** [comment]
@ondraczsk not "Український". "Українська мова" is right.

**Comment by ondraczsk** [comment]
ok> fixed to Українська мова

**Comment by MasterWolf** [comment]
@ondraczsk now ok! :+1:

**Comment by ondraczsk** [comment]
:)

**Comment by inxomnyaa** [comment]
update, then merged.

**Comment by MasterWolf** [comment]
@ondraczsk update your branch

**Comment by ondraczsk** [comment]
why?

**Comment by MasterWolf** [comment]
@ondraczsk so you dont see this "This branch has conflicts that must be resolved" ??

**Comment by MasterWolf** [comment]
@ondraczsk if you dont know how, i will do this changes.

**Comment by MasterWolf** [comment]
@ondraczsk you can close it now... its in my p.r.

**Comment by MasterWolf** [comment]
its here now... https://github.com/ClearSkyTeam/ClearSky/pull/290

**Comment by ondraczsk** [comment]
ok

**Pull request closed without merging**
