### PR TITLE
Create DoritoCraft

### PR DESCRIPTION
**Pull request by Dorito1639**

### CODE REVIEW

**Comment by ScandiePlay** [comment]
`Kill yourself`
^ Nope ~ Admin

**Comment by HimbeersaftLP** [comment]
WTF XD

**Comment by robske110** [comment]
Lol?

**Comment by inxomnyaa** [comment]
Ban for spam? @robske110

**Comment by robske110** [comment]
I don't even know what kind of spam this should be

**Comment by inxomnyaa** [comment]
hm. Useless spam?

**Comment by robske110** [comment]
No, wtf spam

**Comment by inxomnyaa** [comment]
Actually idc, its just a troll

**Pull request closed without merging**
