### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by connectfd**
Visit Site www.clearsky.org

Uptading Apache  follow link https://github.com/BeatNet/-Apache-Web-Server-for-ClearSky/blob/master/README.md

### CODE REVIEW

**Comment by robske110** [comment]
What in the world are you doing

**Comment by daniktheboss** [comment]
Wtf??

**Comment by Aericio** [comment]
What the hell is this?

**Comment by inxomnyaa** [comment]
wtf that grammar.

**Comment by Aericio** [comment]
Dan could make a 10/10 better website...
(and I could w/ cloudflare ^.^)

**Comment by inxomnyaa** [comment]
@Aericio thx. @BeatNet that site is also empty for me. Also @aodzip already has/had a domain (you really paid for a .com domain? -.-)

**Comment by Aericio** [comment]
Saaame. Site is empty. Thought it was my cache or something.

**Pull request closed without merging**
