### PR TITLE
Update Player.php

### PR DESCRIPTION
**Pull request by marcosvkp**
error from uuid_>toBinary()

### CODE REVIEW

**Comment by MarcoDiGio** [comment]
I think this can cause issue

**Comment by ghost** [comment]
i thought the same @BlackShadow1, but idk is this "Piece" of code is needed.

**Comment by Aericio** [comment]
Doesn't this make some plugins not work because some plugins need uuids?

**Comment by robske110** [comment]
Wtf is this for?

**Comment by inxomnyaa** [comment]
Error in your plugins if so.

**Pull request closed without merging**
