### PR TITLE
Fix THE INFAMOUS MEMORY LEAK

### PR DESCRIPTION
**Pull request by dktapps**
This commit, simple though it looks, fixes the horrible memory leak that PocketMine and all its forks have been suffering from since forever. Tested this on Genisys and it works flawlessly.

### CODE REVIEW

**Comment by lolcraftboy** [comment]
y cant wait for tish fix

**Comment by inxomnyaa** [comment]
And why exactly should you use close instead of kill? kill sets health to 0, then next tick its removed using close. That way plugins could cancel it as long as i know.

**Comment by lolcraftboy** [comment]
@thebigsmileXD its working

**Comment by robske110** [comment]
Oops, wanted to press comment...
Anyways isn't the function removeEntity a core function?

**Comment by dktapps** [comment]
@thebigsmileXD You don't _want_ to be able to cancel it. The problem here, as briefly as I can summarize it, is that entities are leaked on chunk unload.

_Before patch:_
- Chunk is unloaded and saved. All entities on the chunk are saved. Level::removeEntity is called on all entities in that chunk to remove them.
- Level::removeEntity kills non-player entities. Result is items and XP being spawned in an unloaded chunk.
- Movement updates to these entitities (falling checks etc.) trigger requests to the blocks around the entities. Because the entities are in unloaded chunks, these requests cause the chunks to be reloaded. When the chunk is reloaded, the saved entities are spawned again.
- Process repeats, leaking more and more entities until memory limit is exhausted.

_After patch:_
- Chunk is unloaded and saved. All entities on the chunk are saved. Level::removeEntity is called on all entities in that chunk to remove them.
- Because Level::removeEntity now uses close() instead of kill(), no items or exp are dropped, which prevents the leak from beginning.

**Comment by robske110** [comment]
Ah

**Comment by robske110** [comment]
Makes total sense

**Comment by robske110** [comment]
Ok, so apperently level ticking is before entitybasetick?

**Comment by robske110** [comment]
👍

**Comment by inxomnyaa** [comment]
Fixes a bug i reported month ago in the group

**Comment by inxomnyaa** [comment]
photo_2016-06-26_17-34-04

**Comment by robske110** [comment]
?

**Comment by lolcraftboy** [comment]
y tink a gone hate clearsky  -_-

**Comment by robske110** [comment]
What?

**Comment by lolcraftboy** [comment]
-_-  ym so dum

**Comment by lolcraftboy** [comment]
y gone stop with  be en noob ......

**Comment by robske110** [comment]
First things first: Learn english before trying to name someone noob in english

**Comment by inxomnyaa** [comment]
@lolcraftboy Banned from Repo

**Comment by lolcraftboy** [comment]
Ok

**Comment by lolcraftboy** [comment]
@thebigsmileXD ym sorry ):

**Pull request merged**
