### PR TITLE
Small typo

### PR DESCRIPTION
**Pull request by robske110**

### CODE REVIEW

**Comment by inxomnyaa** [comment]
AAHHRGGHHH FUCK GITHUB

**Comment by inxomnyaa** [comment]
Almost deleted it

**Comment by robske110** [comment]
You deleted it :P

**Comment by robske110** [comment]
I think i have to revoke your access to my fork

**Comment by MasterWolf** [comment]
AHHAHAHAHAHAHA LOLOLOLOL!

**Comment by Aericio** [comment]
XD rip

**Pull request merged**
