### PR TITLE
[WIP] Win10 fixes

### PR DESCRIPTION
**Pull request by robske110**
DO N O T MERGE THIS
NO TESTING AT ALL HAS BEEN PERFORMED.

Hi there,
we need testing for this PR. For those interested in the changes: https://github.com/iTXTech/Genisys/pull/1621

ToDo:
- fix any found crashes
- remove genisys headers

### CODE REVIEW

**Comment by robske110** [comment]
and we have conflicts

**Comment by dktapps** [comment]
https://github.com/iTXTech/Genisys/commit/0049295dda7606ea725d04e3fbf99c11d5f6eeb5

**Comment by dktapps** [comment]
https://github.com/iTXTech/Genisys/commit/810ef4179f8d411016e43a216628588522cd61a6

**Comment by inxomnyaa** [comment]
@dktapps What is this for?

**Comment by dktapps** [comment]
@thebigsmileXD fix plugin crashes

**Comment by Aericio** [comment]
Nice taaaaag.

**Comment by inxomnyaa** [comment]
MergeMergeMerge

**Comment by robske110** [comment]
Tested?

**Comment by inxomnyaa** [comment]
ah, you woke up. you need to fix the stuff @dktapps mentioned above

**Comment by robske110** [comment]
will do asap

**Comment by robske110** [comment]
And look at the secound point in todo. Should i do it or should we just leave 'em in?

**Comment by Aericio** [comment]
1000000% remove.

**Comment by inxomnyaa** [comment]
@robske110 remove, but mention @dktapps friendly. Like i did for beito in cauldron/flower pots

**Comment by robske110** [comment]
will rebase that one out

**Comment by dktapps** [comment]
I'll fix it. Leave it to me.

**Comment by dktapps** [comment]
NOT DONE YET. Just fixed an absolute shitload of mess and merge conflicts.

**Comment by dktapps** [comment]
Okay, CI passed. One problem down, several more to go.

**Comment by robske110** [comment]
Did you now just completly start from scratch? Or did you just squash evrything

**Comment by dktapps** [comment]
@robske110 Squashed everything, nuked some unrelated commits off and rebased on top of php7

**Comment by robske110** [comment]
👍😍

**Comment by dktapps** [comment]
Will continue work as soon as my recycle bin finishes emptying. (Laptop is lagging sooo bad right now)

**Comment by dktapps** [comment]
ClearSky did not have a count check in deepEquals, that was causing lots of bugs. Fixed. Please continue testing.

**Comment by robske110** [comment]
Wtf are you doing

**Comment by inxomnyaa** [comment]
@robske110 me? Fixing general bugs that occur, why?

**Comment by dktapps** [comment]
Why is that formatting commit on this branch? That isn't related to this PR. Also, the merge commits -_-

**Comment by robske110** [comment]
WARNING REBASING, DROPPING UNRELATED COMMITS, PUSHING THEM TO MASTER

**Comment by inxomnyaa** [comment]
@dktapps accidental non-switch.

I think its ready to merge. my server runs for some days now, no crashes.
(I'll check enchanting table again, i think when @dktapps rebased, my fixes where removed)

**Pull request merged**
