### PR TITLE
FIX COMPILE ERROR

### PR DESCRIPTION
**Pull request by fengberd**
Excuse me??

### CODE REVIEW

**Comment by Aericio** [comment]
There _are_ no compile errors?

**Comment by SalmonDE** [comment]
What do you expect by removing these lines?

**Comment by robske110** [comment]
This PR causes a compile (parse) error

**Comment by aodzip** [comment]
He point out these function are duplicated.
Edit : and CI was failed because "no test commands" , seems not failed by code error

**Comment by robske110** [comment]
Oh Ci broke again

**Comment by robske110** [comment]
it looks like due to very invalid cloning the CIs failed

**Comment by robske110** [comment]
oh you're at the php5 branch wich isn't built by the CIs anymore

**Comment by robske110** [comment]
Please use the php5 branch from this tree: https://github.com/ClearSkyTeam/ClearSky/tree/3e0f27355c88cf4e8c3dd692c114159732686dff

**Comment by Aericio** [comment]
Aodzip is back? :O

**Pull request merged**
