### PR TITLE
Update UKR from ENG in README.md

### PR DESCRIPTION
**Pull request by MasterWolf**

### CODE REVIEW

**Comment by MasterWolf** [comment]
@thebigsmileXD need to push here changes which made @ondraczsk ? Because i think he dont know how to update branch :/

**Comment by MasterWolf** [comment]
I mean these changes
https://github.com/ClearSkyTeam/ClearSky/pull/289

**Comment by ondraczsk** [comment]
yes, i don't now :/

**Comment by MasterWolf** [comment]
ok so wait...

**Comment by MasterWolf** [comment]
@thebigsmileXD done

**Comment by MasterWolf** [comment]
wait do not merge yet! I will do some changes.

**Comment by MasterWolf** [comment]
@thebigsmileXD now ready to merge! :+1:

**Pull request merged**
