### PR TITLE
old api plugins can load now part 1

### PR DESCRIPTION
**Pull request by lolcraftboy**

### CODE REVIEW

**Comment by lolcraftboy** [comment]
tish work now

**Comment by inxomnyaa** [comment]
https://travis-ci.org/ClearSkyTeam/ClearSky/builds/135424087
I see how it works.

**Comment by lolcraftboy** [comment]
o wow -_-

**Comment by SalmonDE** [comment]
@thebigsmileXD Well, it looks like it does work.

**Comment by inxomnyaa** [comment]
Travis doesnt load them. Also its incorrect to use outdated plugins.

**Comment by robske110** [comment]
Trabis is broken

**Pull request closed without merging**
