### PR TITLE
Fixes damage showing up when cancelled (PHP5)

### PR DESCRIPTION
**Pull request by DaPigGuy**

### CODE REVIEW

**Comment by 2449673842** [comment]
players can't join the game because of timeout

**Comment by 2449673842** [comment]
@MCPEPIG

**Comment by 2449673842** [comment]
取中…RestartMe v1.1.0
[10:37:06] [Server thread/WARNING]: ----- ClearSky Auto Updater -----
[10:37:06] [Server thread/WARNING]: It appears you're running a CuttingEdge build, it means you are using src or a custom build
[10:37:06] [Server thread/WARNING]: If you want to run a production server, please use a phar provided by our Jenkins server for better performance
[10:37:06] [Server thread/WARNING]: If you are running a custom build, please remember that the ClearSky Team won't support this version
[10:37:06] [Server thread/WARNING]: ----- -------------------------- -----
[10:37:06] [Server thread/INFO]: 开启中…ZhyProtect v2

**Comment by 2449673842** [comment]
what's that mean?

**Comment by 2449673842** [comment]
l am a chinese who can only use a litter english, l am so aorry for that.

**Comment by 2449673842** [comment]
l must ask you many

**Comment by DaPigGuy** [comment]
This has been tested on 2 servers and players can join perfectly on both.

**Comment by 2449673842** [comment]
CAN I SEND A PICTURE TO YOU

**Comment by DaPigGuy** [comment]
K

**Comment by 2449673842** [comment]
[11:17:18] [Server thread/NOTICE]: Player data not found for "2386313880", creating new                                                                                                                                                                                        profile
[11:17:18] [Server thread/INFO]: 2386313880[/112.132.73.97:19132] logged in with entity                                                                                                                                                                                        id 1 at (world, 128, 70.2, 128)
[11:17:28] [Server thread/INFO]: 2386313880[/112.132.73.97:19132] logged out due to time                                                                                                                                                                                       out

**Comment by 2449673842** [comment]
look

**Comment by 2449673842** [comment]
[11:15:41] [Server thread/WARNING]: Non-packaged ClearSky installation detected, do not use on production.
[11:15:41] [Server thread/INFO]: Loading pocketmine.yml...
[11:15:41] [Server thread/INFO]: Loading server properties...
[11:15:41] [Server thread/INFO]: Enable MainLogger to file
[11:15:41] [Server thread/INFO]: Selected English (eng) as the base language
[11:15:41] [Server thread/INFO]: Starting Minecraft: PE server version v0.15.0 beta
[11:15:41] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[11:15:43] [Server thread/INFO]: This server is running ClearSky version 1.1 "Sunrise" (API 1.13.1) Build CuttingEdge
[11:15:43] [Server thread/INFO]: ClearSky is distributed under the LGPL License
[11:15:45] [Server thread/WARNING]: ----- ClearSky Auto Updater -----
[11:15:45] [Server thread/WARNING]: It appears you're running a CuttingEdge build, it me                                                                                                                                                                                       ans you are using src or a custom build
[11:15:45] [Server thread/WARNING]: If you want to run a production server, please use a                                                                                                                                                                                        phar provided by our Jenkins server for better performance
[11:15:45] [Server thread/WARNING]: If you are running a custom build, please remember t                                                                                                                                                                                       hat the ClearSky Team won't support this version
[11:15:45] [Server thread/WARNING]: ----- -------------------------- -----
[11:15:45] [Server thread/INFO]: Preparing level "world"
[11:15:45] [Server thread/INFO]: Starting GS4 status listener
[11:15:45] [Server thread/INFO]: Setting query port to 19132
[11:15:45] [Server thread/INFO]: Query running on 0.0.0.0:19132
[11:15:45] [Server thread/INFO]: Default game type: Survival Mode
[11:15:45] [Server thread/INFO]: Done (5.07s)! For help, type "help" or "?"
[11:17:18] [Server thread/NOTICE]: Player data not found for "2386313880", creating new                                                                                                                                                                                        profile
[11:17:18] [Server thread/INFO]: 2386313880[/112.132.73.97:19132] logged in with entity                                                                                                                                                                                        id 1 at (world, 128, 70.2, 128)
[11:17:28] [Server thread/INFO]: 2386313880[/112.132.73.97:19132] logged out due to time

**Comment by 2449673842** [comment]
that's all

**Comment by DaPigGuy** [comment]
I didnt test for php5 just php7 :stuck_out_tongue_winking_eye:

**Comment by 2449673842** [comment]
ok

**Comment by 2449673842** [comment]
how can i get next php555

**Comment by 2449673842** [comment]
When the next version of the PHP5

**Comment by Aericio** [comment]
Download a PHP7 bin...
Windows: https://bintray.com/pocketmine/PocketMine/Windows-PHP-Binaries
Linux: https://bintray.com/pocketmine/PocketMine/Unix-PHP-Binaries
Download ClearSky PHP7 (0.15.0)
https://github.com/ClearSkyTeam/ClearSky/tree/php7-0.15
And please stop that spam ;-;

**Pull request merged**
