### PR TITLE
Possible fix for #458

### PR DESCRIPTION
**Pull request by DaPigGuy**
This might fix the 2nd issue in #458

### CODE REVIEW

**Comment by DaPigGuy** [comment]
NOTE: This is not tested!

**Comment by robske110** [comment]
I think it only implements InventoryHolder...

**Comment by DaPigGuy** [comment]
The class has its own getItem() function.

**Comment by DaPigGuy** [comment]
It also implements Container which has a getItem() function too :stuck_out_tongue_winking_eye:

**Comment by inxomnyaa** [comment]
thx anyways

**Pull request closed without merging**
