### PR TITLE
Fix lag with players on a bad network

### PR DESCRIPTION
**Pull request by ghost**
I 've tested it on my wifi [ps my wifi is not as fast ] it works well

### CODE REVIEW

**Comment by SalmonDE** [comment]
I remember this thing from Genisys I think

**Comment by ghost** [comment]
@SalmonGER en from steadfast2

**Comment by robske110** [comment]
This basically changes two versions

**Comment by inxomnyaa** [comment]
wow. 90% of this pr is: removed breakline

**Comment by robske110** [comment]
Yea, will redo the value changes manully

**Pull request closed without merging**
