### PR TITLE
Fix #460

### LINKED ISSUE #460: Command::unregister() doesnt work

### PR DESCRIPTION
**Pull request by DaPigGuy**
It fixes #460. It has been tested and works.

### CODE REVIEW

**Comment by Aericio** [comment]
Clap clap.

**Comment by DaPigGuy** [comment]
The aliases of the command still function though :/

**Comment by robske110** [comment]
Don't make known Commands public! Do create a function removeCommand($label) in simplecommandmap

**Comment by DaPigGuy** [comment]
Ok, wait a bit.

**Comment by robske110** [comment]
Ok

**Comment by DaPigGuy** [comment]
Done, it's been tested btw.

**Comment by robske110** [comment]
https://github.com/MCPEPIG/ClearSky/pull/2

**Pull request merged**
