### PR TITLE
Xbox auth

### PR DESCRIPTION
**Pull request by robske110**
ToDo:
- fix any found crashes

### CODE REVIEW

**Comment by robske110** [comment]
travis seems to be dumb too

**Comment by DaPigGuy** [comment]
Merge!

**Comment by Aericio** [comment]
Merrrrrge!

**Comment by daniktheboss** [comment]
Wait... so now everyone will have to login to Xbox for servers like lbsg?

**Comment by Aericio** [comment]
I believe its optional?

**Comment by daniktheboss** [comment]
Oh ok... but what is it for? Security or what

**Comment by Aericio** [comment]
I guess it could be like extra layer of security. It could also prevent
hackers, if you think about it. Banning them once (as long as xbox auth is
enabled) would probably disable them from hacking again on your server.

**Comment by daniktheboss** [comment]
Ohhhh smart :D

**Comment by SalmonDE** [comment]
Actually I guess there are still a few errors which need to be fixed. (See in Telegram group)

**Comment by robske110** [comment]
Can you pls test this branch and report any crashes to me?

**Comment by daniktheboss** [comment]
Hey guys I don't know where to ask so what is the best anti cheat?

**Comment by SalmonDE** [comment]
@daniktheboss players who report cheaters. 👍

**Comment by HimbeersaftLP** [comment]
If you merge this, players with Windows Phone and Amazon Fire won't be able to join ClearSky servers anymore because Windows Phone and Amazon Fire Minecraft has no Xbox login...

**Comment by inxomnyaa** [comment]
@HimbeersaftLP they will, its optional, not pflicht

**Comment by HimbeersaftLP** [comment]
> @HimbeersaftLP they will, its optional, not pflicht

So you talk in Denglisch now? :P

**Comment by robske110** [comment]
Will be merged when i finally find time to test this.

**Comment by daniktheboss** [comment]
Dan... can you please help imagicalmine? They can't get client to connect

**Comment by robske110** [comment]
Isn't imagicalmine dead? And the 0.15 update was performed by md

**Comment by daniktheboss** [comment]
Really? Oh thanks.. and yea they are but they are reactive..  if u could help them... lol

**Comment by inxomnyaa** [comment]
According to IM: I don't help a pack of kiddies and noobs.

**Comment by Aericio** [comment]
According to dan, all Imagicalmine does is copy code.

**Comment by HimbeersaftLP** [comment]
> I don't help a pack of kiddies and noobs.

Wheeee, we no kidddiiieesss mum, Dan is evil, muuummmm, we no kiddes you stupid kiddy. XD

**Comment by Aericio** [comment]
###### ***ban alert ban alert***

**Comment by HimbeersaftLP** [comment]
I was just kidding...

**Comment by SalmonDE** [comment]
@robske110 
Warning: require_once(D:\Minecraft\Server\PocketMine-MP\src/spl/ClassLoader.php): failed to open stream: No such file or directory in D:\Minecraft\Server\PocketMine-MP\src\pocketmine\PocketMine.php on line 88

Fatal error: require_once(): Failed opening required 'D:\Minecraft\Server\PocketMine-MP\src/spl/ClassLoader.php' (include_path='.;.\ext') in D:\Minecraft\Server\PocketMine-MP\src\pocketmine\PocketMine.php on line 88
bin\php\php.exe: Exit 255

**Comment by robske110** [comment]
Testing this myself now (git submodule: wtf???)

**Comment by inxomnyaa** [comment]
That was a pretty short time testing and only you testet

**Pull request merged**
