### PR TITLE
Translation: nld

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by inxomnyaa** [comment]
Won't merge for a week, maybe you find more.

**Comment by robske110** [comment]
Please, as thebigsmileXD pointed out commit everything to this pr, we'll squash and merge then. We don't want the repo to be spammed with small translation commits.

**Comment by ghost** [comment]
yes i get it

**Comment by robske110** [comment]
Looks like you've found everything, will be merged tomorrow

**Comment by Aericio** [comment]
> will be merged tomorrow

3 days later...

**Pull request merged**
