### PR TITLE
MCPE 0.14.0 Build 4 Compatibility

### PR DESCRIPTION
**Pull request by SalmonDE**

### CODE REVIEW

**Comment by PocketKiller** [comment]
you sure packet changed?

**Comment by SalmonDE** [comment]
@PocketKiller Yes, i tested it. :)

**Comment by SalmonDE** [comment]
screenshot_20160202-212816
Is that enough to prove it? @PocketKiller

**Comment by aodzip** [comment]
conflicts , seems you don't use the latest code to make this change

**Comment by Wolfurama** [comment]
Mmm where can i get it i,m newbie :/ because jenkins is offline v':

**Comment by aodzip** [comment]
it should online now

**Comment by Wolfurama** [comment]
Lol fine

**Pull request closed without merging**
