### PR TITLE
Pocketmine yml translater @UE Team

### PR DESCRIPTION
**Pull request by aodzip**
Follow me , add all translate for pocketmine.yml and installer

### CODE REVIEW

**Comment by aodzip** [comment]
What need we do:
Copy/Create a translate file in \src\pocketmine\lang\Installer\ and uncomment it in \src\pocketmine\wizard\InstallerLang.php
Tip: You can just copy out it from "old lang" and rename it into 3char language file

Create json translate map in \src\pocketmine\resources
Tip: there is a demo for eng , I think it is easy to understand

**Comment by haniokasai** [comment]
ill do it!

**Comment by robske110** [comment]
I'll do german

**Comment by haniokasai** [comment]
ill make json version....
https://github.com/ClearSkyTeam/ClearSky/blob/master/src/pocketmine/resources/pocketmine-jp.yml

**Comment by haniokasai** [comment]
https://github.com/ClearSkyTeam/ClearSky/commit/642a57e386dd25c87584f24e14cb4cd8914ce583

is this true?

**Comment by TheKillerTacos** [comment]
I'll do Spanish

**Comment by inxomnyaa** [comment]
outdated base code, conflicts

**Pull request closed without merging**
