### PR TITLE
How about this?

### PR DESCRIPTION
**Pull request by robske110**
For the Windoof Fix?

### CODE REVIEW

**Comment by robske110** [comment]
Answer?

**Comment by inxomnyaa** [comment]
@robske110 Closed with unmerged commits

**Comment by robske110** [comment]
Wtf 
I wanted to know WHY you have closed it.
You're slowly turning into Intyre

**Comment by inxomnyaa** [comment]
Because.. No difference in Windows. I've tried it. I still get the same piece of poop issue

**Comment by robske110** [comment]
Oh, you finally noticed that you have access to my fork

**Pull request closed without merging**
