### PR TITLE
more versions support

### PR DESCRIPTION
**Pull request by dries-c**

### CODE REVIEW

**Comment by DaPigGuy** [comment]
:+1:

**Comment by dries-c** [comment]
thx

**Comment by aodzip** [comment]
As I known , 0.14 have a different unpack method

**Comment by dries-c** [comment]
view beta tester from https://github.com/PeratX/BetaTester

**Comment by robske110** [comment]
Close this. It's stupid to allow 0.14 clients to join on the 0.13 server. Client or Server will crash

**Comment by dries-c** [comment]
ok

**Pull request closed without merging**
