### PR TITLE
Yuck!

### PR DESCRIPTION
**Pull request by DaPigGuy**

### CODE REVIEW

**Comment by inxomnyaa** [comment]
😂

**Comment by inxomnyaa** [comment]
Btw. Use isSurvival. Else you cant damage in gm adventure

**Comment by robske110** [comment]
How the **\* didn't travis catch the missing ()?

**Comment by inxomnyaa** [comment]
@robske110 i think because the code isn't called actually.

**Comment by inxomnyaa** [comment]
Anyways, this needs fixes. I guess theres a ; missing

**Comment by DaPigGuy** [comment]
Fixed

**Comment by inxomnyaa** [comment]
@MCPEPIG i see no changes.

**Comment by ghost** [comment]
@thebigsmileXD in adventure mode you can get hurt

**Comment by inxomnyaa** [comment]
@SkygridRex Plz, learn to read.
**_Btw. Use isSurvival. Else you cant damage in gm adventure**_

**Comment by ghost** [comment]
@thebigsmileXD so i play in my adventure world and i can get hurt, the only difference in Survival and Adventure Mode it the possibility to break blocks. Did you say mind Espectador Mode?

**Comment by ghost** [comment]
@thebigsmileXD i'm not a schwachsinnige i know read

**Comment by inxomnyaa** [comment]
Then read

**Comment by robske110** [comment]
What's up with this now?

**Comment by inxomnyaa** [comment]
Still not ->isSurvival()

**Comment by robske110** [comment]
Close this -_- I'm annyoed

**Comment by inxomnyaa** [comment]
#395

**Pull request closed without merging**
