### PR TITLE
Fix for golden apples & fish

### PR DESCRIPTION
**Pull request by DaPigGuy**

### CODE REVIEW

**Comment by DaPigGuy** [comment]
This pull request fixes the enchanted golden apples looking like regular golden apples, cooked salmon looking like cooked fish, & raw salmon, clownfish, & pufferfish looking like raw fish. You can now merge this @aodzip or @thebigsmileXD

**Comment by aodzip** [comment]
…Have you fully tested?

**Comment by DaPigGuy** [comment]
I've only tested the ids. I'll test know if you want

**Comment by DaPigGuy** [comment]
Just tested, it works.

**Comment by inxomnyaa** [comment]
But please finally stop naming your commits ":3"

**Pull request merged**
