### PR TITLE
Cleaning up the readme

### PR DESCRIPTION
**Pull request by robske110**
(English part)

### CODE REVIEW

**Comment by aodzip** [comment]
I wont merge this now XD , because I make huge bug in Redstone System , I am shame .
JUST WAIT ME！

**Comment by robske110** [comment]
Ok :D

**Comment by ghost** [comment]
> Unlimit player join(set max-players to -1 in server.properties)

Would it be UnlimitED

**Comment by robske110** [comment]
Oh yes

**Comment by robske110** [comment]
Is redstone now finsihed :P

**Comment by aodzip** [comment]
Yes , but this PR conflicted

**Comment by robske110** [comment]
I will rebase it soon

**Pull request closed without merging**
