### PR TITLE
Support for all 0.14.*

### PR DESCRIPTION
**Pull request by MCUnderground**

### CODE REVIEW

**Comment by SalmonDE** [comment]
I think that doesn't work. Since @robske110 already tried that.

**Comment by MCUnderground** [comment]
It should lol

**Comment by MCUnderground** [comment]
Someone can try it maybe?

**Comment by SalmonDE** [comment]
@MCUnderground #429 That's @robske110's pr.

**Comment by MCUnderground** [comment]
Wait i seen something on others

**Comment by MCUnderground** [comment]
Check last file i edited

**Comment by SalmonDE** [comment]
Lol if this works later (or maybe now?) you have done great work. :D

**Comment by Pub4Game** [comment]
It works.

https://github.com/Nukkit/Nukkit/commit/c003f873d1d1714309af2c4e2eb0293a86f9418a

**Comment by SalmonDE** [comment]
Crashed for me. (Joined with 0.14.1 Client)

Error: Call to a member function toBinary() on null
File: /src/pocketmine/Player
Line: 2228
Type: E_ERROR

Code:
[2219]                      $this->directDataPacket($pk);
[2220]                  }
[2221]                  $this->close("", $message, false);
[2222]                  break;
[2223]              }
[2224]              $this->randomClientId = $packet->clientId;
[2225]              $this->loginData = ["clientId" => $packet->clientId, "loginData" => null];
[2226] 
[2227]              $this->uuid = $packet->clientUUID;
[2228]              $this->rawUUID = $this->uuid->toBinary();
[2229]              $this->clientSecret = $packet->clientSecret;
[2230]              $valid = true;
[2231]              $len = strlen($packet->username);
[2232]              if($len > 16 or $len < 3){
[2233]                  $valid = false;
[2234]              }
[2235]              for($i = 0;$i < $len and $valid;++$i){
[2236]                  $c = ord($packet->username{$i});
[2237]                  if(($c >= ord("a") and $c <= ord("z")) or
[2238]($c >= ord%28"A"%29 and $c <= ord%28"Z"%29) or

**Comment by Pub4Game** [comment]
Only 0.14.3

**Comment by robske110** [comment]
There is no possibilty to do this

**Comment by MCUnderground** [comment]
Actually it works in genisys

**Comment by inxomnyaa** [comment]
@MCUnderground This is not genisys.

**Pull request closed without merging**
