### PR TITLE
Fix Spelling errors in Spanish and changed some stuff

### PR DESCRIPTION
**Pull request by ghost**
Fixed Spelling errors such like spaces and , (comas), and also added "All player can join now on 0.14" on Spanish, so i recommend to merge after merging #429, or do whatever you want!

### CODE REVIEW

**Comment by robske110** [comment]
Is this finished?

**Comment by robske110** [comment]
And #429 doesn't quite work

**Comment by ghost** [comment]
@thebigsmileXD gave no **_uhm, sorry.. what?!**_

**Comment by inxomnyaa** [comment]
_cough_

**Comment by ghost** [comment]
hehehe

**Pull request merged**
