### PR TITLE
Fixes for enchanted golden apple

### PR DESCRIPTION
**Pull request by DaPigGuy**

### CODE REVIEW

**Comment by inxomnyaa** [comment]
Thats not the bug, fix works (that 2 letters ;) )

**Comment by DaPigGuy** [comment]
There's also another $eatItem instead of $eatenItem that I fixed...

**Comment by DaPigGuy** [comment]
and those 2 parenthesis I deleted shouldn't be there ;)

**Comment by DaPigGuy** [comment]
Wait nvm you fixed the other $eatItem too

**Comment by inxomnyaa** [comment]
> There's also another $eatItem instead of $eatenItem that I fixed...

You haven't changed anything with these, am i wrong?

> and those 2 parenthesis I deleted shouldn't be there ;)

They need to. Wether you don't have full hunger or you have a special item :P

**Comment by DaPigGuy** [comment]
Oh, im stupid Lel

**Pull request closed without merging**
