### PR TITLE
Much better!

### PR DESCRIPTION
**Pull request by ghost**
Why would you reupload PocketMine with some changes instead of forking the original project? I'm fine with it if you would at least give them some credit. But no... you want to feel like you made your own server software. It's not because you make some changes to a project, that you can claim it. You even removed all the copyright notices and disclaimers from every file.
I agree that PocketMine has many problems, but if everyone starts creating their own version of PM that won't help the community forward. Create a fork so you and PM can merge some of each others commits.

The readme file of this project is just ridiculous:
`"Ultra Fast", "About 20 times faster than offical PM repo"` 
Ever heard of a benchmark? Without some actual proof this is just bs.
`"We may take code from other GPL licenced projects, but most features are fully-rewritten for ClearSky"` 
No you take all code from other projects and change a few things.

And by the way you are not allowed to remove the copyright notices.

### CODE REVIEW

**Comment by PocketKiller** [comment]
OMG WIES SO AWESOME :0

**Comment by inxomnyaa** [comment]
You want proof? Install it and you'll see. -.-"

Go and fix MyPlot instead of complaining

**Comment by inxomnyaa** [comment]
And ledgendsofpe, the bug master core ;)

**Comment by ghost** [comment]
The work you have put into this project is amazing, but why in this project? Wouldn't it be better if everyone collaborated? I know you didn't create the terrible readme or remove all copyright notices. Please put your effort into helping the right projects.

**Comment by aodzip** [comment]
Please leave us alone if you don't like our repo.

**Comment by jyyyyylim** [comment]
uhm sir @wiez if yu have nothing good to say den plz dont say it/post it (whatever). if clearsky "copied" pocketmine as u said, why is it not as **laggy** as pocketmine??? why does it have more features then pocketmine??? if yu dont even have an answer for thag den leave clearsky alone sir

**Comment by jyyyyylim** [comment]
pssh humans these days -.-"

**Comment by ghost** [comment]
ClearSky is Based on the PM Core, almost everything Changed, Much Faster, Less Crappier, and more eficent (sorry if misspelled) and it crashes even less that original PM, And also, PM is open source, you may modify it, but not claim it as 100% yours, and in CS the most of the code changed,
and this is just like Mozilla did with Firefox, Firefox (newest) is based on Chromium (Google Chrome open source Project) and i dont see Firefox or Mozilla giving Chrome any credit, might be different licenses, but in this world, No one barely cares, :D

**Comment by ghost** [comment]
And also removing the GNU Licenses, and server Core Clean up of code made it faster, why load a heavy Phar full of GNU Licenses and useless code than rather using Clean Code for faster Perfomance!?

EDIT: tried to see the changes he made, Chrome Crashed XD

**Comment by inxomnyaa** [comment]
They do. In the information tab in firefox (version info)

**Comment by ghost** [comment]
Ha-ha didn't see that...

**Comment by ghost** [comment]
This project is still violating the PocketMine license. PocketMine is licensed under GPL v3 and you are not allowed to change that to GPL v2. Also you are not allowed to remove copyright notices.

> uhm sir @wiez if yu have nothing good to say den plz dont say it/post it (whatever). if clearsky "copied" pocketmine as u said, why is it not as laggy as pocketmine??? why does it have more features then pocketmine??? if yu dont even have an answer for thag den leave clearsky alone sir

It's just as laggy as PocketMine. If the ClearSky team found anything that greatly improved the performance (x20 as they claim), why not collaborate and share these improvements with the PocketMine community so we can all go forward? I do agree that ClearSky has more features, but if all developers had put their efforts into helping PocketMine instead of creating their "own" version, all of these features would now be in PocketMine.

> ClearSky is Based on the PM Core, almost everything Changed, Much Faster, Less Crappier, and more eficent (sorry if misspelled) and it crashes even less that original PM, And also, PM is open source, you may modify it, but not claim it as 100% yours, and in CS the most of the code changed,
> and this is just like Mozilla did with Firefox, Firefox (newest) is based on Chromium (Google Chrome open source Project) and i dont see Firefox or Mozilla giving Chrome any credit, might be different licenses, but in this world, No one barely cares, :D

They added quite a lot of extra stuff, but didn't change much of the original PM Core. Compare the source code yourself and you will see. "Much Faster, Less Crappier, and more eficent and it crashes even less" is just a fantasy. How can software developed by a team of experienced people who think before pushing commits be crappier and is less stable than software developed by a team where some people have almost no prior programming experience? And it doesn't matter if almost all code has changed or not, copyrighted work remains copyrighted.

> And also removing the GNU Licenses, and server Core Clean up of code made it faster, why load a heavy Phar full of GNU Licenses and useless code than rather using Clean Code for faster Perfomance!?
> 
> EDIT: tried to see the changes he made, Chrome Crashed XD

Removing the license is not allowed and it won't make a difference in performance. You might win a couple milliseconds on startup, that's it.

**Comment by robske110** [comment]
We didn't remove the license at all, and if we realy used GPL v2 we will correct that as soon as possible.
And just because removing the license header to not make the phar so big it is't violating anything. We are even massivley planning to make PRs on pm but they never get merged

**Comment by Aericio** [comment]
The developers at PocketMine should be fixing their own things.

**Comment by robske110** [comment]
> They added quite a lot of extra stuff, but didn't change much of the original PM Core. Compare the source code yourself and you will see. "Much Faster, Less Crappier, and more eficent and it crashes even less" is just a fantasy. How can software developed by a team of experienced people who think before pushing commits be crappier and is less stable than software developed by a team where some people have almost no prior programming experience? And it doesn't matter if almost all code has changed or not, copyrighted work remains copyrighted.

Hey, @thebigsmileXD and @aodzip are one of the best core devs around here. (My list (For CoreDev): @shogihcp @PEMapModder @PeratX @Aodzip @thebigsmileXD )

**Comment by robske110** [comment]
> It's just as laggy as PocketMine. If the ClearSky team found anything that greatly improved the performance (x20 as they claim), why not collaborate and share these improvements with the PocketMine community so we can all go forward? I do agree that ClearSky has more features, but if all developers had put their efforts into helping PocketMine instead of creating their "own" version, all of these features would now be in PocketMine.

No, they don't accept PRs and as already stated, we're planning to make PRs (And we're doing it already)

**Comment by ghost** [comment]
CS Is faster than PM, if you know how to configure it!!

**Pull request closed without merging**
