### PR TITLE
update particle ids from pmmp

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
i go to sleap so see you tomorrow

**Comment by robske110** [comment]
Thanks,
but don't just bluntly copy without proper notice. And dktapps is still working on particles.

**Comment by robske110** [comment]
and you forgot to re-enable particles anyways

**Comment by dktapps** [comment]
This isn't even from pmmp, it's from Steadfast or Elywing. Notice how 19 is repeated?

**Comment by robske110** [comment]
even worse.

**Comment by robske110** [comment]
TYPE_TOWN_AURA that is one confusing name

**Comment by dktapps** [comment]
It's actually referred to as SuspendedTownParticle in the code

**Comment by inxomnyaa** [comment]
TYPE_TOWN_AURA  == mycelium/´bedrock particles

**Pull request closed without merging**
