### PR TITLE
"Fish Button" Yay!!

### PR DESCRIPTION
**Pull request by ghost**
**Fish Button work! I already Test it!**

### CODE REVIEW

**Comment by PocketKiller** [comment]
Please close this, it does not work, and it is copied from Genisys/ImagicalMine, you don't know what you're doing with my commit.

**Comment by inxomnyaa** [comment]
There is no button at all, also i coded this once.

**Comment by ghost** [comment]
The button is already there, just that the Rod Isnt working :(

**Comment by ghost** [comment]
i just take it xD

**Pull request closed without merging**
