### PR TITLE
Fix BanCommand (restore original+1fix) 

### LINKED ISSUE #333: Ban Message
image
Shows this when you do /ban. This layout is kind of like a /tempban layout
**Normal Ban Message**
I think the default in Pocketmine is: Banned by admin. Reason: (reason)

### PR DESCRIPTION
**Pull request by robske110**
Fixes #333

### CODE REVIEW

**Comment by inxomnyaa** [comment]
This was intended and works.

**Comment by robske110** [comment]
Nope it just messes everything up

**Comment by inxomnyaa** [comment]
I can ban without problems.

**Comment by inxomnyaa** [comment]
there, so you are happy

**Pull request merged**
