### PR TITLE
Updated all recipes & Sorted

### PR DESCRIPTION
**Pull request by KyoshiHikari**
So i updated all recipes, added new recipes & sorted out from Shapeless over Shaped to BigShaped.

Regards

### CODE REVIEW

**Comment by aodzip** [comment]
@thebigsmileXD Is this okay?

**Comment by aodzip** [comment]
looks fine

**Comment by KyoshiHikari** [comment]
Yes it's okay, should work :D 

Regards

**Comment by aodzip** [comment]
merged

**Comment by KyoshiHikari** [comment]
Nice thx :)
But i can help you fix all things, what i know :D if that's okay

Regards :)

**Comment by aodzip** [comment]
That is welcome

**Pull request merged**
