### PR TITLE
Looks better on Server Lists and green version on client

### PR DESCRIPTION
**Pull request by robske110**
If the client is 0.13.2 it is green and shows 0.13 if it is 0.13.1 or 0.13 it will be red but display 0.13

### CODE REVIEW

**Comment by aodzip** [comment]
Have you tested ?
Can that .x show correctly in MCPE client

**Comment by robske110** [comment]
Will test, please hold on!

**Comment by robske110** [comment]
I can join (0.13.2)
I somehow don't see an modt of any server you could test it:
robskebueba.no-ip.biz:6450 //This is no advertisment, it is my scrappy test server!

**Comment by aodzip** [comment]
You can join , but I think that .x will blown motd up
I have try this before motd went away

**Comment by robske110** [comment]
Hmm right

**Comment by robske110** [comment]
The question now is:
We want the client to display 0.13 and always red (and all 0.13.x can join) [Current state of this PR]
Or we want the client to display 0.13.2 green (and on older versions red) but all 0.13.x can still join

**Comment by Adam1609** [comment]
Can you do that. Somehow playerjoinEvent caused this into red @@

**Comment by Driesboy** [comment]
Update protocol like imagicalmine

**Comment by aodzip** [comment]
Can they get uni join but give out a green version?

**Comment by robske110** [comment]
I think so let me check something

**Comment by robske110** [comment]
Currently testing it

**Comment by robske110** [comment]
0.13.2: showing 0.13 in green
0.13.1: Testing
0.13: Testing

**Comment by PocketKiller** [comment]
@robske110 TF how did you add labels... invited?

**Comment by robske110** [comment]
Yes ;)

**Comment by robske110** [comment]
0.13.1: Server crash

**Comment by robske110** [comment]
0.13 untested

**Comment by PocketKiller** [comment]
@robske110 I have an 0.13.0 .apk I'll test it out

**Comment by robske110** [comment]
robskebueba.no-ip.biz:6450 if Server Closed appears the Server crashed lol

**Comment by aodzip** [comment]
I have tested , cash

**Pull request closed without merging**
