### PR TITLE
Added german language file for installer

### PR DESCRIPTION
**Pull request by jarne**

### CODE REVIEW

**Comment by SalmonDE** [comment]
Finally someone does it <3

**Comment by jarne** [comment]
I know 😆

**Comment by robske110** [comment]
:D

**Comment by inxomnyaa** [comment]
Can't choose it anyways ;)

**Comment by SalmonDE** [comment]
Oh, yeah
https://github.com/ClearSkyTeam/ClearSky/blob/php7/src/pocketmine/wizard/InstallerLang.php#L12

**Comment by jarne** [comment]
Fixed with #628

**Pull request merged**
