### PR TITLE
Added 0.15 items to creative inventory

### PR DESCRIPTION
**Pull request by DaPigGuy**
Missing tipped arrows :pig:

### CODE REVIEW

**Comment by daniktheboss** [comment]
1. Rcon crashes, 2.cant join due to timeout?

**Comment by DaPigGuy** [comment]
Are you using PHP5?

**Comment by daniktheboss** [comment]
Um.. I'm not sure.. how do I check?

**Comment by DaPigGuy** [comment]
Show me results for when you do /version

**Comment by DaPigGuy** [comment]
because ClearSky for PHP5 might be broken

**Comment by daniktheboss** [comment]
Ok php7

**Comment by inxomnyaa** [comment]
@daniktheboss open an issue

**Comment by inxomnyaa** [comment]
Is Item::PISTON defined?
LEAD should be LEASH.

**Comment by robske110** [comment]
because ClearSky for PHP5 might be broken
WTF? It's more stable than php7

**Comment by Muqsit** [comment]
Have you tested this?

**Comment by DaPigGuy** [comment]
Item::PISTON was already there.

**Pull request merged**
