### PR TITLE
I translated README.md to Ukrainian language!

### PR DESCRIPTION
**Pull request by MasterWolf**

### CODE REVIEW

**Comment by aodzip** [comment]
Englash(Global)
Chinese
German(owner and letter order)
A B C D E F G H I J     K L M N O P Q R S T U              V W X Y Z 
                             (Japanese)                       (Ukrainian)

**Comment by aodzip** [comment]
You know what I mean .
But anyway , thanks for your translate

**Comment by MasterWolf** [comment]
@aodzip can you merge it plz?

**Comment by aodzip** [comment]
You should put your translate under Japanese translate.

**Comment by MasterWolf** [comment]
@aodzip but wait i dont know japanese :/

**Comment by aodzip** [comment]
I think you misunderstand my words . I will change this tomorrow.

**Comment by SalmonDE** [comment]
Aodzip wants your translation below the japanese translation. @MasterWolf

**Comment by MasterWolf** [comment]
@SalmonGER ok thx. i will remake it tomorrow!

**Comment by MasterWolf** [comment]
Or no i will do this just now!

**Comment by MasterWolf** [comment]
@aodzip @SalmonGER done!

**Pull request merged**
